[2021-04-19 12:51:02] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:02] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [8]
[2021-04-19 12:51:02] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [8]
[2021-04-19 12:51:02] INFO: db_pool sleep [223] ms before retry connection [8] ...
[2021-04-19 12:51:03] INFO: appx_spec [classes] [
  'string',    'number',
  'boolean',   'null',
  'primitive', 'array',
  'object',    'expression',
  'statement', 'jsx',
  'any'
]
[2021-04-19 12:51:03] INFO: appx_spec [types] [
  'react/element',         'react/html',
  'react/state',           'react/effect',
  'react/context',         'appx/form',
  'appx/dialog',           'appx/input/text',
  'appx/input/textarray',  'appx/input/switch',
  'appx/input/select',     'appx/input/tabular',
  'appx/input/collection', 'appx/input/submit',
  'appx/input/reset',      'appx/input/rule',
  'appx/table',            'appx/table/column',
  'js/null',               'js/string',
  'js/number',             'js/boolean',
  'js/object',             'js/array',
  'js/import',             'js/expression',
  'js/statement',          'js/function',
  'js/call',               'js/condition',
  'js/map',                'js/reduce',
  'js/filter',             'mui/style',
  'mui/theme',             'route/path',
  'route/context',         'appx/api'
]
[2021-04-19 12:51:03] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:03] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [7]
[2021-04-19 12:51:03] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [7]
[2021-04-19 12:51:03] INFO: db_pool sleep [620] ms before retry connection [7] ...
[2021-04-19 12:51:03] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:03] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [6]
[2021-04-19 12:51:03] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [6]
[2021-04-19 12:51:03] INFO: db_pool sleep [1438] ms before retry connection [6] ...
[2021-04-19 12:51:05] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:05] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [5]
[2021-04-19 12:51:05] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [5]
[2021-04-19 12:51:05] INFO: db_pool sleep [1807] ms before retry connection [5] ...
[2021-04-19 12:51:07] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:07] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [4]
[2021-04-19 12:51:07] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [4]
[2021-04-19 12:51:07] INFO: db_pool sleep [2152] ms before retry connection [4] ...
[2021-04-19 12:51:09] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:09] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [3]
[2021-04-19 12:51:09] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [3]
[2021-04-19 12:51:09] INFO: db_pool sleep [2930] ms before retry connection [3] ...
[2021-04-19 12:51:12] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:12] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [2]
[2021-04-19 12:51:12] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [2]
[2021-04-19 12:51:12] INFO: db_pool sleep [3070] ms before retry connection [2] ...
[2021-04-19 12:51:15] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:15] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [1]
[2021-04-19 12:51:15] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [1]
[2021-04-19 12:51:15] INFO: db_pool sleep [3739] ms before retry connection [1] ...
[2021-04-19 12:51:18] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:18] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [0]
[2021-04-19 12:51:18] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [0]
[2021-04-19 12:51:18] ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
[2021-04-19 12:51:18] ERROR: Failed to load [SELECT * FROM _realm_app WHERE deleted = 0] {"query":"SELECT * FROM _realm_app WHERE deleted = 0","map_def":[{"name":"sql_realm_by_app","key":["$@.namespace","$@.app_name"],"value":"$@"},{"name":"sql_app_by_realm","key":["$@.realm","$@.namespace","$@.app_name"],"value":"$@"}]}
[2021-04-19 12:51:18] Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
    at query (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:84:22)
    at Query._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:138:21)
    at Query.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:205:13
    at Handshake.onConnect (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Protocol.handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/Protocol.js:369:14)
    at PoolConnection.Connection._handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:418:18)
[2021-04-19 12:51:18] Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
    at query (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:84:22)
    at Query._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:138:21)
    at Query.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:205:13
    at Handshake.onConnect (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Protocol.handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/Protocol.js:369:14)
    at PoolConnection.Connection._handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:418:18)
[2021-04-19 12:51:18] ERROR: load_cache_for("realm", null) - failed ! -- Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
[2021-04-19 12:51:18] INFO: load_cache_for("realm", null) - reconcile in 209 sec(s)
[2021-04-19 12:51:18] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:18] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [8]
[2021-04-19 12:51:18] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [8]
[2021-04-19 12:51:18] INFO: db_pool sleep [316] ms before retry connection [8] ...
[2021-04-19 12:51:19] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:19] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [7]
[2021-04-19 12:51:19] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [7]
[2021-04-19 12:51:19] INFO: db_pool sleep [634] ms before retry connection [7] ...
[2021-04-19 12:51:19] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:19] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [6]
[2021-04-19 12:51:19] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [6]
[2021-04-19 12:51:19] INFO: db_pool sleep [1229] ms before retry connection [6] ...
[2021-04-19 12:51:21] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:21] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [5]
[2021-04-19 12:51:21] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [5]
[2021-04-19 12:51:21] INFO: db_pool sleep [1989] ms before retry connection [5] ...
[2021-04-19 12:51:23] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:23] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [4]
[2021-04-19 12:51:23] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [4]
[2021-04-19 12:51:23] INFO: db_pool sleep [2203] ms before retry connection [4] ...
[2021-04-19 12:51:25] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:25] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [3]
[2021-04-19 12:51:25] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [3]
[2021-04-19 12:51:25] INFO: db_pool sleep [2933] ms before retry connection [3] ...
[2021-04-19 12:51:28] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:28] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [2]
[2021-04-19 12:51:28] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [2]
[2021-04-19 12:51:28] INFO: db_pool sleep [3499] ms before retry connection [2] ...
[2021-04-19 12:51:31] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:31] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [1]
[2021-04-19 12:51:31] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [1]
[2021-04-19 12:51:31] INFO: db_pool sleep [3809] ms before retry connection [1] ...
[2021-04-19 12:51:35] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:35] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [0]
[2021-04-19 12:51:35] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [0]
[2021-04-19 12:51:35] ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0]
[2021-04-19 12:51:35] ERROR: Failed to load [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] {"query":"SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0","map_def":[{"name":"sql_auth_grant_by_role","key":["$@.namespace","$@.app_name","$@.role_name","$@.grant_type","$@.grant_name"],"value":"$@"}]}
[2021-04-19 12:51:35] Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0]
    at query (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:84:22)
    at Query._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:138:21)
    at Query.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:205:13
    at Handshake.onConnect (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Protocol.handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/Protocol.js:369:14)
    at PoolConnection.Connection._handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:418:18)
[2021-04-19 12:51:35] Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0]
    at query (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:84:22)
    at Query._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:138:21)
    at Query.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:205:13
    at Handshake.onConnect (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Protocol.handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/Protocol.js:369:14)
    at PoolConnection.Connection._handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:418:18)
[2021-04-19 12:51:35] ERROR: load_cache_for("auth", null) - failed ! -- Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0]
[2021-04-19 12:51:35] INFO: load_cache_for("auth", null) - reconcile in 276 sec(s)
[2021-04-19 12:51:35] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:35] ERROR: [SELECT * FROM namespace WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [8]
[2021-04-19 12:51:35] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [8]
[2021-04-19 12:51:35] INFO: db_pool sleep [208] ms before retry connection [8] ...
[2021-04-19 12:51:35] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:35] ERROR: [SELECT * FROM namespace WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [7]
[2021-04-19 12:51:35] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [7]
[2021-04-19 12:51:35] INFO: db_pool sleep [990] ms before retry connection [7] ...
[2021-04-19 12:51:36] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:36] ERROR: [SELECT * FROM namespace WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [6]
[2021-04-19 12:51:36] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [6]
[2021-04-19 12:51:36] INFO: db_pool sleep [1006] ms before retry connection [6] ...
[2021-04-19 12:51:37] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:37] ERROR: [SELECT * FROM namespace WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [5]
[2021-04-19 12:51:37] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [5]
[2021-04-19 12:51:37] INFO: db_pool sleep [1653] ms before retry connection [5] ...
[2021-04-19 12:51:39] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:39] ERROR: [SELECT * FROM namespace WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [4]
[2021-04-19 12:51:39] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [4]
[2021-04-19 12:51:39] INFO: db_pool sleep [2274] ms before retry connection [4] ...
[2021-04-19 12:51:41] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:41] ERROR: [SELECT * FROM namespace WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [3]
[2021-04-19 12:51:41] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [3]
[2021-04-19 12:51:41] INFO: db_pool sleep [2807] ms before retry connection [3] ...
[2021-04-19 12:51:44] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:44] ERROR: [SELECT * FROM namespace WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [2]
[2021-04-19 12:51:44] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [2]
[2021-04-19 12:51:44] INFO: db_pool sleep [3077] ms before retry connection [2] ...
[2021-04-19 12:51:47] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:47] ERROR: [SELECT * FROM namespace WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [1]
[2021-04-19 12:51:47] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [1]
[2021-04-19 12:51:47] INFO: db_pool sleep [3815] ms before retry connection [1] ...
[2021-04-19 12:51:51] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:51] ERROR: [SELECT * FROM namespace WHERE deleted = 0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [0]
[2021-04-19 12:51:51] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [0]
[2021-04-19 12:51:51] ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM namespace WHERE deleted = 0]
[2021-04-19 12:51:51] ERROR: Failed to load [SELECT * FROM namespace WHERE deleted = 0] {"query":"SELECT * FROM namespace WHERE deleted = 0","map_def":[{"name":"sql_namespaces","key":["$@.namespace"],"value":"$@"}]}
[2021-04-19 12:51:51] Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM namespace WHERE deleted = 0]
    at query (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:84:22)
    at Query._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:138:21)
    at Query.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:205:13
    at Handshake.onConnect (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Protocol.handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/Protocol.js:369:14)
    at PoolConnection.Connection._handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:418:18)
[2021-04-19 12:51:51] Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM namespace WHERE deleted = 0]
    at query (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:84:22)
    at Query._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:138:21)
    at Query.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:205:13
    at Handshake.onConnect (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Protocol.handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/Protocol.js:369:14)
    at PoolConnection.Connection._handleNetworkError (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:418:18)
[2021-04-19 12:51:51] ERROR: load_cache_for("namespace", null) - failed ! -- Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM namespace WHERE deleted = 0]
[2021-04-19 12:51:51] INFO: load_cache_for("namespace", null) - reconcile in 260 sec(s)
[2021-04-19 12:51:52] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:52] ERROR: [SELECT
                    app_deployment.namespace,
                    app_deployment.app_name,
                    app_deployment.app_deployment,
                    app_deployment.app_runtime,
                    app_deployment.app_ver,
                    app_deployment.app_rev,
                    app_deployment.app_deployment_spec
                FROM app_deployment
                WHERE
                    app_deployment.deleted=0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [8]
[2021-04-19 12:51:52] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [8]
[2021-04-19 12:51:52] INFO: db_pool sleep [494] ms before retry connection [8] ...
[2021-04-19 12:51:52] INFO: found app-x path [app-x/api]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/route/RouterProvider]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/theme/GlobalStyleProvider]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/theme/dark]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/theme]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/theme/light]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/util/Page]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/util/ThemeBadge]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/util/UserBadge]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_api]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_dialog]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_form]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_input_collection]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_input_reset]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_input_rule]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_input_select]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_input_submit]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_input_switch]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_input_tabular]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_input_text]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_input_textarray]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_table]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/appx_table_column]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/classes]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_array]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_boolean]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_call]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_condition]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_expression]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_filter]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_function]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_import]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_map]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_null]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_number]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_object]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_reduce]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_statement]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/js_string]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/mui_style]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/mui_theme]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/react_context]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/react_effect]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/react_element]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/react_html]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/react_state]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/route_context]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/spec/route_path]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/redux/store]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/redux/reducer]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/redux/reducer/roleReducer]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/redux/reducer/userReducer]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/Dialog]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/InputCollection]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/InputProvider]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/Form]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/InputReset]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/InputSelect]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/InputSubmit]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/InputSwitch]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/InputTabular]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/InputTextArray]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/Table]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/core/InputText]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/API]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Asterisk]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Bracket]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Branch]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Calculator]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Code]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Context]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Css]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/CurlyBracket]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Dialog]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Effect]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Facebook]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Form]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/FunctionCall]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Function]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Google]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Html]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Import]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/InputCollection]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/InputReset]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/InputSelect]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/InputRule]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/InputSubmit]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/InputSwitch]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/InputTabular]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/InputTextArray]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/InputText]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Live]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Pointer]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Preview]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/React]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Provider]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Database]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Redo]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Filter]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Reset]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Router]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Route]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/State]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Style]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Table]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Save]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/TableColumn]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Text]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Undo]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Widget]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/icon/Theme]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/page/error/NotFoundView]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/page/landing/Unsplash_bg]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/page/landing/YouTube_fs]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/component/AutoSuggest]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/component/ControlledEditor]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/component/InputField]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/component/InputFieldArray]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/component/InputFieldTabular]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/component/InputProperties]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/component/TextFieldArray]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/NavProvider]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/UI_Builder]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/route/RouteAddDialog]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/route/RouteMenu]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/route/RouteTree]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/route/util]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/route/RouteProvider]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/route/RouteDeleteDialog]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/component/ComponentAddDialog]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/component/ComponentDeleteDialog]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/component/ComponentTree]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/component/ComponentMenu]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/component/ComponentProvider]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/component/util]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/PreviewJson]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/PreviewProvider]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/PreviewSource]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/PreviewTabs]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/PropEditor]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/SyntaxDeleteDialog]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/SyntaxAddDialog]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/SyntaxMenu]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/SyntaxMoveDialog]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/SyntaxProvider]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/SyntaxTree]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/TestEditor]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/util_base]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/PreviewYaml]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/YamlEditor]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/util_generate]
[2021-04-19 12:51:52] INFO: found app-x path [app-x/builder/ui/syntax/util_parse]
[2021-04-19 12:51:53] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:53] ERROR: [SELECT
                    app_deployment.namespace,
                    app_deployment.app_name,
                    app_deployment.app_deployment,
                    app_deployment.app_runtime,
                    app_deployment.app_ver,
                    app_deployment.app_rev,
                    app_deployment.app_deployment_spec
                FROM app_deployment
                WHERE
                    app_deployment.deleted=0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [7]
[2021-04-19 12:51:53] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [7]
[2021-04-19 12:51:53] INFO: db_pool sleep [884] ms before retry connection [7] ...
[2021-04-19 12:51:54] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:54] ERROR: [SELECT
                    app_deployment.namespace,
                    app_deployment.app_name,
                    app_deployment.app_deployment,
                    app_deployment.app_runtime,
                    app_deployment.app_ver,
                    app_deployment.app_rev,
                    app_deployment.app_deployment_spec
                FROM app_deployment
                WHERE
                    app_deployment.deleted=0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [6]
[2021-04-19 12:51:54] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [6]
[2021-04-19 12:51:54] INFO: db_pool sleep [1218] ms before retry connection [6] ...
[2021-04-19 12:51:55] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:55] ERROR: [SELECT
                    app_deployment.namespace,
                    app_deployment.app_name,
                    app_deployment.app_deployment,
                    app_deployment.app_runtime,
                    app_deployment.app_ver,
                    app_deployment.app_rev,
                    app_deployment.app_deployment_spec
                FROM app_deployment
                WHERE
                    app_deployment.deleted=0] -- Error: connect ECONNREFUSED 127.0.0.1:3338 [5]
[2021-04-19 12:51:55] INFO: retry connection error -- Error: connect ECONNREFUSED 127.0.0.1:3338 [5]
[2021-04-19 12:51:55] INFO: db_pool sleep [1670] ms before retry connection [5] ...
[2021-04-19 12:51:57] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:57] ERROR: [SELECT
                    app_deployment.namespace,
                    app_deployment.app_name,
                    app_deployment.app_deployment,
                    app_deployment.app_runtime,
                    app_deployment.app_ver,
                    app_deployment.app_rev,
                    app_deployment.app_deployment_spec
                FROM app_deployment
                WHERE
                    app_deployment.deleted=0] -- Error: Connection lost: The server closed the connection. [4]
[2021-04-19 12:51:57] INFO: retry connection error -- Error: Connection lost: The server closed the connection. [4]
[2021-04-19 12:51:57] INFO: db_pool sleep [2046] ms before retry connection [4] ...
[2021-04-19 12:51:59] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:51:59] ERROR: [SELECT
                    app_deployment.namespace,
                    app_deployment.app_name,
                    app_deployment.app_deployment,
                    app_deployment.app_runtime,
                    app_deployment.app_ver,
                    app_deployment.app_rev,
                    app_deployment.app_deployment_spec
                FROM app_deployment
                WHERE
                    app_deployment.deleted=0] -- Error: Connection lost: The server closed the connection. [3]
[2021-04-19 12:51:59] INFO: retry connection error -- Error: Connection lost: The server closed the connection. [3]
[2021-04-19 12:51:59] INFO: db_pool sleep [2682] ms before retry connection [3] ...
[2021-04-19 12:52:01] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:52:01] ERROR: [SELECT
                    app_deployment.namespace,
                    app_deployment.app_name,
                    app_deployment.app_deployment,
                    app_deployment.app_runtime,
                    app_deployment.app_ver,
                    app_deployment.app_rev,
                    app_deployment.app_deployment_spec
                FROM app_deployment
                WHERE
                    app_deployment.deleted=0] -- Error: Connection lost: The server closed the connection. [2]
[2021-04-19 12:52:01] INFO: retry connection error -- Error: Connection lost: The server closed the connection. [2]
[2021-04-19 12:52:01] INFO: db_pool sleep [3004] ms before retry connection [2] ...
[2021-04-19 12:52:04] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:52:04] ERROR: [SELECT
                    app_deployment.namespace,
                    app_deployment.app_name,
                    app_deployment.app_deployment,
                    app_deployment.app_runtime,
                    app_deployment.app_ver,
                    app_deployment.app_rev,
                    app_deployment.app_deployment_spec
                FROM app_deployment
                WHERE
                    app_deployment.deleted=0] -- Error: Connection lost: The server closed the connection. [1]
[2021-04-19 12:52:04] INFO: retry connection error -- Error: Connection lost: The server closed the connection. [1]
[2021-04-19 12:52:04] INFO: db_pool sleep [3613] ms before retry connection [1] ...
[2021-04-19 12:52:08] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:52:08] ERROR: [SELECT
                    app_deployment.namespace,
                    app_deployment.app_name,
                    app_deployment.app_deployment,
                    app_deployment.app_runtime,
                    app_deployment.app_ver,
                    app_deployment.app_rev,
                    app_deployment.app_deployment_spec
                FROM app_deployment
                WHERE
                    app_deployment.deleted=0] -- Error: Connection lost: The server closed the connection. [0]
[2021-04-19 12:52:08] INFO: retry connection error -- Error: Connection lost: The server closed the connection. [0]
[2021-04-19 12:52:08] ERROR: unrecoverable error, all connection retries has failed [SELECT
                    app_deployment.namespace,
                    app_deployment.app_name,
                    app_deployment.app_deployment,
                    app_deployment.app_runtime,
                    app_deployment.app_ver,
                    app_deployment.app_rev,
                    app_deployment.app_deployment_spec
                FROM app_deployment
                WHERE
                    app_deployment.deleted=0]
[2021-04-19 12:52:08] (node:73479) UnhandledPromiseRejectionWarning: Error: ERROR: unrecoverable error, all connection retries has failed [SELECT
                    app_deployment.namespace,
                    app_deployment.app_name,
                    app_deployment.app_deployment,
                    app_deployment.app_runtime,
                    app_deployment.app_ver,
                    app_deployment.app_rev,
                    app_deployment.app_deployment_spec
                FROM app_deployment
                WHERE
                    app_deployment.deleted=0]
    at query (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:84:22)
    at Query._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:138:21)
    at Query.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:205:13
    at Handshake.onConnect (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/Protocol.js:404:18
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
[2021-04-19 12:52:08] (node:73479) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[2021-04-19 12:52:08] (node:73479) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2021-04-19 12:54:48] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:54:48] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [8]
[2021-04-19 12:54:48] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [8]
[2021-04-19 12:54:48] INFO: db_pool sleep [83] ms before retry connection [8] ...
[2021-04-19 12:54:48] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:54:48] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [7]
[2021-04-19 12:54:48] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [7]
[2021-04-19 12:54:48] INFO: db_pool sleep [823] ms before retry connection [7] ...
[2021-04-19 12:54:49] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:54:49] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [6]
[2021-04-19 12:54:49] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [6]
[2021-04-19 12:54:49] INFO: db_pool sleep [1042] ms before retry connection [6] ...
[2021-04-19 12:54:50] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:54:50] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [5]
[2021-04-19 12:54:50] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [5]
[2021-04-19 12:54:50] INFO: db_pool sleep [1797] ms before retry connection [5] ...
[2021-04-19 12:54:52] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:54:52] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [4]
[2021-04-19 12:54:52] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [4]
[2021-04-19 12:54:52] INFO: db_pool sleep [2203] ms before retry connection [4] ...
[2021-04-19 12:54:54] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:54:54] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [3]
[2021-04-19 12:54:54] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [3]
[2021-04-19 12:54:54] INFO: db_pool sleep [2729] ms before retry connection [3] ...
[2021-04-19 12:54:57] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:54:57] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [2]
[2021-04-19 12:54:57] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [2]
[2021-04-19 12:54:57] INFO: db_pool sleep [3058] ms before retry connection [2] ...
[2021-04-19 12:55:00] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:00] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [1]
[2021-04-19 12:55:00] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [1]
[2021-04-19 12:55:00] INFO: db_pool sleep [3515] ms before retry connection [1] ...
[2021-04-19 12:55:03] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:03] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [0]
[2021-04-19 12:55:03] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [0]
[2021-04-19 12:55:03] ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
[2021-04-19 12:55:03] ERROR: Failed to load [SELECT * FROM _realm_app WHERE deleted = 0] {"query":"SELECT * FROM _realm_app WHERE deleted = 0","map_def":[{"name":"sql_realm_by_app","key":["$@.namespace","$@.app_name"],"value":"$@"},{"name":"sql_app_by_realm","key":["$@.realm","$@.namespace","$@.app_name"],"value":"$@"}]}
[2021-04-19 12:55:03] Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
    at query (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:84:22)
    at Query._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:138:21)
    at Query.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:205:13
    at Handshake.onConnect (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Handshake.ErrorPacket (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Handshake.js:125:8)
    at Protocol._parsePacket (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
[2021-04-19 12:55:03] Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
    at query (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:84:22)
    at Query._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:138:21)
    at Query.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:205:13
    at Handshake.onConnect (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Handshake.ErrorPacket (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Handshake.js:125:8)
    at Protocol._parsePacket (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
[2021-04-19 12:55:03] ERROR: load_cache_for("realm", null) - failed ! -- Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
[2021-04-19 12:55:03] INFO: load_cache_for("realm", null) - reconcile in 354 sec(s)
[2021-04-19 12:55:37] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:37] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [8]
[2021-04-19 12:55:37] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [8]
[2021-04-19 12:55:37] INFO: db_pool sleep [245] ms before retry connection [8] ...
[2021-04-19 12:55:38] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:38] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [7]
[2021-04-19 12:55:38] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [7]
[2021-04-19 12:55:38] INFO: db_pool sleep [588] ms before retry connection [7] ...
[2021-04-19 12:55:38] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:38] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [6]
[2021-04-19 12:55:38] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [6]
[2021-04-19 12:55:38] INFO: db_pool sleep [1354] ms before retry connection [6] ...
[2021-04-19 12:55:40] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:40] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [5]
[2021-04-19 12:55:40] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [5]
[2021-04-19 12:55:40] INFO: db_pool sleep [1672] ms before retry connection [5] ...
[2021-04-19 12:55:41] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:41] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [4]
[2021-04-19 12:55:41] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [4]
[2021-04-19 12:55:41] INFO: db_pool sleep [2499] ms before retry connection [4] ...
[2021-04-19 12:55:44] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:44] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [3]
[2021-04-19 12:55:44] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [3]
[2021-04-19 12:55:44] INFO: db_pool sleep [2546] ms before retry connection [3] ...
[2021-04-19 12:55:46] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:46] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [2]
[2021-04-19 12:55:46] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [2]
[2021-04-19 12:55:46] INFO: db_pool sleep [3456] ms before retry connection [2] ...
[2021-04-19 12:55:50] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:50] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [1]
[2021-04-19 12:55:50] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [1]
[2021-04-19 12:55:50] INFO: db_pool sleep [3689] ms before retry connection [1] ...
[2021-04-19 12:55:54] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:54] ERROR: [SELECT * FROM _realm_app WHERE deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [0]
[2021-04-19 12:55:54] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [0]
[2021-04-19 12:55:54] ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
[2021-04-19 12:55:54] ERROR: Failed to load [SELECT * FROM _realm_app WHERE deleted = 0] {"query":"SELECT * FROM _realm_app WHERE deleted = 0","map_def":[{"name":"sql_realm_by_app","key":["$@.namespace","$@.app_name"],"value":"$@"},{"name":"sql_app_by_realm","key":["$@.realm","$@.namespace","$@.app_name"],"value":"$@"}]}
[2021-04-19 12:55:54] Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
    at query (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:84:22)
    at Query._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:138:21)
    at Query.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:205:13
    at Handshake.onConnect (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Handshake.ErrorPacket (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Handshake.js:125:8)
    at Protocol._parsePacket (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
[2021-04-19 12:55:54] Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
    at query (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:84:22)
    at Query._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/src/db/db.js:138:21)
    at Query.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:205:13
    at Handshake.onConnect (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Handshake.ErrorPacket (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/sequences/Handshake.js:125:8)
    at Protocol._parsePacket (/Users/shiwabal/go/src/github.trusted.visa.com/parsec/poodle-appx/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
[2021-04-19 12:55:54] ERROR: load_cache_for("realm", null) - failed ! -- Error: ERROR: unrecoverable error, all connection retries has failed [SELECT * FROM _realm_app WHERE deleted = 0]
[2021-04-19 12:55:54] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:54] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [8]
[2021-04-19 12:55:54] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [8]
[2021-04-19 12:55:54] INFO: db_pool sleep [297] ms before retry connection [8] ...
[2021-04-19 12:55:54] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:54] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [7]
[2021-04-19 12:55:54] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [7]
[2021-04-19 12:55:54] INFO: db_pool sleep [908] ms before retry connection [7] ...
[2021-04-19 12:55:55] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:55] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [6]
[2021-04-19 12:55:55] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [6]
[2021-04-19 12:55:55] INFO: db_pool sleep [1005] ms before retry connection [6] ...
[2021-04-19 12:55:56] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:56] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [5]
[2021-04-19 12:55:56] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [5]
[2021-04-19 12:55:56] INFO: db_pool sleep [1721] ms before retry connection [5] ...
[2021-04-19 12:55:58] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:55:58] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [4]
[2021-04-19 12:55:58] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [4]
[2021-04-19 12:55:58] INFO: db_pool sleep [2461] ms before retry connection [4] ...
[2021-04-19 12:56:00] INFO: [DB POOL] connecting to localhost
[2021-04-19 12:56:00] ERROR: [SELECT * FROM _auth_grant WHERE grant_type = 'user' AND deleted = 0] -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [3]
[2021-04-19 12:56:00] INFO: retry connection error -- Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'appx'@'172.17.0.1' (using password: YES) [3]
[2021-04-19 12:56:00] INFO: db_pool sleep [2937] ms before retry connection [3] ...
